# Generated by Django 3.2.5 on 2021-09-02 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_modelsubjects_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsubjects',
            name='sched',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.modelmainform'),
        ),
        migrations.AlterField(
            model_name='modelsubjects',
            name='subjects',
            field=models.TextField(),
        ),
    ]
