# Generated by Django 3.2.5 on 2021-09-02 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210902_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsubjects',
            name='sched',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.modelmainform'),
        ),
    ]
